### ISSUE TITLE
Body Mass Index (BMI) Calculator

### ISSUE THREAD

**Issue by faisalfotoooh** [ritsat/bmi_calculator_app#1]
https://www.diabetes.ca/managing-my-diabetes/tools---resources/body-mass-index-(bmi)-calculator

**Comment by ritsat** [comment]
Here BMI is calculated using **bmi = Weight/(height * height)** formula.
(_Weight in Kg & height in meter_).

Gender & Age is not part of BMI calculation. 

Here it is kept on UI just for information purpose which can be used in further functionalities like sharing  and if anyone want to save/record the BMI data for future purpose.

I hope it will clarify the doubts.
